# Copyright (C) 2019 Antony Chazapis
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

"""
Django settings for exhibition project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u_tf3*%kko1up=d&s)^j@d6(=rgpt=o4-g8b+4%&(=-=$d2n-$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'registrations.apps.RegistrationsConfig',
    'django_countries',
    'social_django',
    'tempus_dominus',
    'crispy_forms',
    'admin_views',
    'impersonate',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'impersonate.middleware.ImpersonateMiddleware',
]

ROOT_URLCONF = 'exhibition.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'registrations.context_processors.exhibition',
                'registrations.context_processors.oauth'
            ],
        },
    },
]

WSGI_APPLICATION = 'exhibition.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


# Uploaded media files

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Authentication with OAuth 2

AUTHENTICATION_BACKENDS = (
    'social_core.backends.open_id.OpenIdAuth',
    'social_core.backends.google.GoogleOpenId',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.google.GoogleOAuth',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SOCIAL_AUTH_URL_NAMESPACE = 'social'

SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {'fields': 'id, name, email'}
SOCIAL_AUTH_FACEBOOK_EXTRA_DATA = [('name', 'name'),
                                   ('email', 'email')]

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = ''
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = ''

SOCIAL_AUTH_TWITTER_KEY = ''
SOCIAL_AUTH_TWITTER_SECRET = ''

SOCIAL_AUTH_FACEBOOK_KEY = ''
SOCIAL_AUTH_FACEBOOK_SECRET = ''


# Form styling with crispy-forms

CRISPY_TEMPLATE_PACK = 'bootstrap4'


# Exhibition name and details

EXHIBITION_NAME = 'NOTOS 2021'
EXHIBITION_URL = 'http://hps.gr/notos2021/'
EXHIBITION_EMAIL = 'notos2021@hps.gr'
EXHIBITION_LOGO = 'notos_2021.jpg'


# Communication language in addition to English

NATIVE_COMMUNICATION_LANGUAGE = ('EL', 'Greek')


# Authorization key to register appointments

APPOINTMENTS_AUTHORIZATION_KEY = 'KEY'


# Privacy policy note shown when creating an account or submiting any form

PRIVACY_POLICY_MESSAGE = 'We shall treat the data you enter with respect. Further details are in our <a href="http://hps.gr/notos2021/index.php/privacy-policy/" target="_blank">Privacy Policy Page</a>. By filling in the form and clicking the SUBMIT button you agree to the terms provided therein as well as to receiving emails from us.'


# Disable exhibit entry forms by explaining why

ENTRY_FORMS_DISABLED_MESSAGE = ''


# Entry forms submit warning

ENTRY_FORMS_SUBMIT_MESSAGE = 'By submitting this Entry Form the Exhibitor accepts the Regulations listed in article 2.1. and confirms the truthfulness of all data entered.'


# Whenever a new commissioner or juror is registered, we email the
# president of the respective federation. Whenever a new exhibitor
# is registered, we email the commissioner of the exhibitors country.
# If we have no commissioner contact, we email to this address (if it exists).

NO_COMMISSIONER_EMAIL = ''


# We note to emails sent to commissioners that any objections should be directed to this email

GENERAL_COMMISSIONER_EMAIL = ''


# Add these recipients to any emails sent

EMAIL_ADDITIONAL_RECIPIENTS = []


# Send all emails only to the additional recipients list

EMAIL_ONLY_ADDITIONAL_RECIPIENTS = False
