from .default import *

import os

SECRET_KEY = ''

DEBUG = False

USE_X_FORWARDED_HOST = True
ALLOWED_HOSTS = ['cometonotos.hps.gr']

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

EMAIL_HOST = 'mail.hps.gr'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'noreply@hps.gr'
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

APPOINTMENTS_AUTHORIZATION_KEY = 'KEY'
# ENTRY_FORMS_HIDDEN = True
# NO_COMMISSIONER_EMAIL = 'info@hps.gr'
