# Generated by Django 2.2.5 on 2019-09-13 11:17

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Miss', 'MISS'), ('Mrs', 'MRS'), ('Dr', 'DR'), ('Mr', 'MR')], default='Mr', max_length=8)),
                ('surname', models.CharField(max_length=128)),
                ('name', models.CharField(help_text='Please include any middle names', max_length=128)),
                ('address', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('commissioner_country', django_countries.fields.CountryField(blank=True, help_text='State here if you are a national commissioner for another country', max_length=2)),
                ('telephone', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=32)),
                ('language', models.CharField(choices=[('Greek', 'EL'), ('English', 'EN')], default='EN', help_text='Communication language', max_length=2)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
