# Generated by Django 2.2.5 on 2019-10-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='accredited_juror',
            field=models.CharField(blank=True, choices=[('FIP', 'FIP'), ('FEPA', 'FEPA'), ('NAT', 'National')], max_length=4),
        ),
    ]
