# Generated by Django 2.2.5 on 2019-09-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('EL', 'Greek')], default='EN', help_text='Communication language', max_length=2),
        ),
        migrations.AlterField(
            model_name='participant',
            name='telephone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='participant',
            name='title',
            field=models.CharField(choices=[('MRS', 'Mrs'), ('DR', 'Dr'), ('MISS', 'Miss'), ('MR', 'Mr')], default='MR', max_length=8),
        ),
    ]
