# Generated by Django 2.2.5 on 2019-09-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateTimeField(blank=True, null=True)),
                ('arrival_flight_number', models.CharField(blank=True, max_length=8)),
                ('departure', models.DateTimeField(blank=True, null=True)),
                ('departure_flight_number', models.CharField(blank=True, max_length=8)),
                ('ticket_price', models.CharField(blank=True, help_text='If to be paid by the Organizing Committee', max_length=64)),
                ('spouse', models.BooleanField()),
                ('spouse_surname', models.CharField(blank=True, max_length=128)),
                ('spouse_name', models.CharField(blank=True, help_text='Include any middle names', max_length=128)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Participant')),
            ],
        ),
    ]
