# Generated by Django 2.2.5 on 2019-09-25 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0002_traveldetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitparticipation',
            options={'verbose_name': 'Exhibit Participation', 'verbose_name_plural': 'Exhibit Participations'},
        ),
        migrations.AlterModelOptions(
            name='traveldetails',
            options={'verbose_name': 'Travel Details', 'verbose_name_plural': 'Travel Details'},
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
