# Generated by Django 2.2.5 on 2019-10-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20191003_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.CharField(default='unknown', max_length=128),
            preserve_default=False,
        ),
    ]
