# Generated by Django 2.2.5 on 2019-09-26 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20190925_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='registrations.Participant'),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_details', to='registrations.Participant'),
        ),
    ]
