# Generated by Django 2.2.5 on 2019-10-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20190926_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='cover',
            field=models.FileField(blank=True, help_text='Provisional introductory page or cover page if literature', upload_to='exhibit/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='participant/'),
        ),
    ]
