# Generated by Django 2.2.5 on 2019-10-03 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20191001_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='commissioner_country',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='language',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='traveldetails',
            name='hotel',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='traveldetails',
            name='hotel_website',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federation', models.CharField(max_length=128)),
                ('commissioner', models.BooleanField()),
                ('jury', models.BooleanField()),
                ('apprentice_jury', models.BooleanField()),
                ('accredited_juror', models.CharField(blank=True, choices=[('FIP', 'FIP'), ('FEPA', 'FEPA')], max_length=4)),
                ('accredited_juror_disciplines', models.CharField(max_length=128)),
                ('team_leader', models.BooleanField()),
                ('team_leader_disciplines', models.CharField(max_length=128)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official', to='registrations.Participant')),
            ],
        ),
    ]
