# Generated by Django 2.2.5 on 2019-11-12 08:02

from django.db import migrations, models
import django.db.models.deletion


def empty_federation_field(apps, schema_editor):
    Appointments = apps.get_model('registrations', 'Appointments')
    for appointments in Appointments.objects.all():
        appointments.federation = None
        appointments.save()


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20191112_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='federation',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.RunPython(empty_federation_field),
        migrations.AlterField(
            model_name='appointments',
            name='federation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='registrations.Federation'),
        ),
    ]
