# Generated by Django 2.2.9 on 2020-03-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_auto_20191228_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='commissioner_email',
            field=models.CharField(blank=True, help_text='Used if no commissioner has registered', max_length=128, null=True),
        ),
    ]
