# Generated by Django 2.2.8 on 2020-04-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_federation_commissioner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='frames',
            field=models.IntegerField(choices=[(0, 'None'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
    ]
