# Generated by Django 2.2.8 on 2020-04-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_auto_20200404_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='isbn',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
