# Generated by Django 2.2.10 on 2021-05-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_auto_20210525_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
