# Generated by Django 2.2.10 on 2021-07-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_exhibit_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='exhibit_class',
            field=models.CharField(choices=[('B1', 'B1. Classe des Champions'), ('C1', 'C1. Traditional Philately'), ('C2', 'C2. Postal History'), ('C3', 'C3. Postal Stationery'), ('C4', 'C4. Aerophilately'), ('C5', 'C5. Astrophilately'), ('C6', 'C6. Revenues'), ('C7', 'C7. Thematic Philately'), ('C8', 'C8. Maximaphily'), ('C9', 'C9. Open Philately'), ('C10', 'C10. Picture Postcards'), ('L1', 'L1. Philatelic Literature – Books of research nature, specialised catalogues'), ('L2', 'L2. Philatelic Literature – Books of promotional and documentary character'), ('L3', 'L3. Philatelic Literature – General catalogues'), ('L4', 'L4. Philatelic Literature – Periodicals'), ('L5', 'L5. Philatelic Literature – Articles (collections of)'), ('L6', 'L6. Philatelic Literature – Websites'), ('L7', 'L7. Philatelic Literature – Software'), ('L8', 'L8. Philatelic Literature – Other digital works'), ('Y1', 'Y1. Youth Philately - Exhibitor’s age (at 1.1.2021) 10-15 years'), ('Y2', 'Y2. Youth Philately - Exhibitor’s age (at 1.1.2021) 16-18 years'), ('Y3', 'Y3. Youth Philately - Exhibitor’s age (at 1.1.2021) 19-21 years'), ('A1', 'A1. Court of Honour (non-competitive)'), ('A2', 'A2. Official Class (non-competitive)'), ('A3', 'A3. Jury Class (non-competitive)'), ('A4', 'A4. Other exhibits (non-competitive)')], max_length=4),
        ),
    ]
