# Generated by Django 2.2.10 on 2021-07-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_auto_20210702_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='jury_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(blank=True, help_text='Include any middle names', max_length=128),
        ),
    ]
